### PR TITLE
feature: Inline reconstruction for jupyter notebook

### PR DESCRIPTION
**Pull request by ShantanuKodgirwar**
This PR allows showing the update of reconstructions using the **default inline backend of a jupyter (IPython) notebook**. Previously, to observe the update of reconstructions within a notebook, one always required specifying an interactive backend such as qt5Agg or TkAgg, etc. Without an interactive backend, all you could see was the progress bar and not the live plots being updated with iterations. This can also be annoying if you are running a headless environment (remote server) and would like to use a jupyter notebook instead of a python script that requires X11 port forwarding for gui based interactive visualizations.

Summary of changes:
- Within the package `PtyLab/Monitor/Plots.py`, the backend is detected and if inline implements the `drawNowIpython` method for updating reconstructions.
- Within `PtyLab/Monitor/Monitor.py`, some warning messages based on performance are specified
- These changes were tested in `jupyter_tutorials/jupyter_tutorials_tutorial_CPM_sim.ipynb` using the interactive as well as the non-interactive backend and also adds some minor changes to this notebook.
- `ipykernel` is made as a compulsory dependency from optional because these new methods require them.
- Minor change with black formatted `PtyLab/Engines/BaseEngine.py`
- Patch version to 0.1.3

**Note: Please merge PR https://github.com/PtyLab/PtyLab.py/pull/58 first as it adds the version 0.1.2**

@roflmaostc @dboonz

### CODE REVIEW

**Comment by roflmaostc** [comment]
ready to merge?

**Comment by ShantanuKodgirwar** [comment]
yup!

**Comment by ShantanuKodgirwar** [comment]
@roflmaostc Considering that PR #58 had a lot of changes (and if version it to 0.2.0), this PR could be 0.1.2 and can be merged before? What do you think?

**Comment by roflmaostc** [comment]
So merging this before?

**Comment by ShantanuKodgirwar** [comment]
yupp. The toml file here needs to be changed from 0.1.3 to 0.1.2 if you okay with it.

**Comment by roflmaostc** [comment]
Yes, looks good. 
Change it and I merge :)

Thanks for your great work and sorry for that slowness.

**Comment by ShantanuKodgirwar** [comment]
No problem :) I understand that there aren't a lot of active python maintainers. Feel free to merge :)

**Pull request merged**
